### ISSUE TITLE
incompatibility with mg.extended 4.x

### ISSUE THREAD

**Issue by Mordsdima** [Apostolique/Apos.Gui#13]
example code doesnt work, here stack trace:
```
Unhandled exception. System.TypeLoadException: Could not load type 'MonoGame.Extended.Point2' from assembly 'MonoGame.Extended, Version=4.0.3.0, Culture=neutral, PublicKeyToken=null'.
   at Apos.Gui.Component.get_Bounds()
   at Apos.Gui.IMGUI.UpdateLayout(GameTime gameTime)
   at MenuScreen.Update(GameTime gameTime) in /home/diman/Documents/ltc/Chronic/Game/Screens/MenuScreen.cs:line 48
   at MonoGame.Extended.Screens.ScreenManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Chronic.GameRoot.Update(GameTime gameTime) in /home/diman/Documents/ltc/Chronic/Game/GameRoot.cs:line 86
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Program.Main() in /home/diman/Documents/ltc/Chronic/Platforms/DesktopGL/Program.cs:line 9
```

and code..
```
public override void Update(GameTime gameTime)
    {
        GuiHelper.UpdateSetup(gameTime);
        _ui.UpdateStart(gameTime);

        // Create your UI.
        MenuPanel.Push();
        if (Button.Put("Show fun").Clicked) {
            _showFun = !_showFun;
        }
        if (_showFun) {
            Label.Put("This is fun!");
        }
        if (Button.Put("Quit").Clicked) {
            Game.Exit();
        }
        MenuPanel.Pop();

        // Call UpdateEnd and UpdateCleanup at the end.
        _ui.UpdateEnd(gameTime);
        GuiHelper.UpdateCleanup();
    }
```

(yes copy-paste)

**Comment by Apostolique** [comment]
Just pushed version 2.1.0 which uses the latest MonoGame.Extended version and fixes the API compatibility issues. Hopefully it works for you.

**Comment by Mordsdima** [comment]
yea, works, thanks

**Comment by Mordsdima** [comment]
Oh, wait, now currently issue with input, it doesnt detect any input, neither keyboard nor mouse (i didnt tried joystick)

**Comment by Mordsdima** [comment]
in example input works thought

**Comment by Apostolique** [comment]
What does your code look like? Are you calling:

```cs
// Call UpdateSetup at the start.
GuiHelper.UpdateSetup(gameTime);
_ui.UpdateStart(gameTime);
```
and later
```cs
// Call UpdateEnd and UpdateCleanup at the end.
_ui.UpdateEnd(gameTime);
GuiHelper.UpdateCleanup();
```

**Comment by Mordsdima** [comment]
yep
